// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/tiagoncardoso/fc/pge/clean-arch/internal/application/usecase"
	"github.com/tiagoncardoso/fc/pge/clean-arch/internal/entity"
	"github.com/tiagoncardoso/fc/pge/clean-arch/internal/event"
	"github.com/tiagoncardoso/fc/pge/clean-arch/internal/infra/database"
	"github.com/tiagoncardoso/fc/pge/clean-arch/internal/infra/web"
	"github.com/tiagoncardoso/fc/pge/clean-arch/pkg/events"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewGetOrdersUseCase(db *sql.DB) *usecase.GetOrdersUseCase {
	orderRepository := database.NewOrderRepository(db)
	getOrdersUseCase := usecase.NewGetOrdersUseCase(orderRepository)
	return getOrdersUseCase
}

func NewGetOrderByIdUseCase(db *sql.DB) *usecase.GetOrderByIdUseCase {
	orderRepository := database.NewOrderRepository(db)
	getOrderByIdUseCase := usecase.NewGetOrderByIdUseCase(orderRepository)
	return getOrderByIdUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderCreated)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))
